name: SAND CI [dev]
run-name: SAND CI
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container: almalinux/9-base
    steps:
      # # reference: https://docs.docker.com/engine/install/ubuntu/
      # # Set up Docker's apt repository.

      # ## Add Docker's official GPG key:
      # - run: sudo apt-get update
      # - run: sudo apt-get install ca-certificates curl
      # - run: sudo install -m 0755 -d /etc/apt/keyrings
      # - run: sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      # - run: sudo chmod a+r /etc/apt/keyrings/docker.asc

      # ## Add the repository to Apt sources:
      # - run: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      # - run: sudo apt-get update

      # # Install the Docker packages.
      # - run: sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      
      # # Verify that the Docker Engine installation is successful by running the hello-world image.
      # - run: sudo docker run hello-world

      # # Download AL9 image
      # - run: docker pull almalinux/9-base

      # # Install ROOT dependencies
      # # https://root.cern/install/dependencies/
      # - run: yum install -y git make cmake gcc-c++ gcc binutils libX11-devel libXpm-devel libXft-devel libXext-devel python openssl-devel
      # - run: yum install -y epel-release
      # # - run: ls -lrt /etc/yum.repos.d
      # # - run: yum config-manager --set-enabled powertools
      # - run: yum -y install xrootd-client-devel xrootd-libs-devel gcc-gfortran pcre-devel mesa-libGL-devel mesa-libGLU-devel glew-devel ftgl-devel mysql-devel fftw-devel cfitsio-devel graphviz-devel libuuid-devel avahi-compat-libdns_sd-devel openldap-devel python-devel python3-numpy libxml2-devel gsl-devel readline-devel qt5-qtwebengine-devel R-devel R-Rcpp-devel R-RInside-devel

      # Install ROOT v6.32.02
      - run: yum install -y root-6.32.02
